// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package skillreview

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Env                  string   `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Echo                 string   `protobuf:"bytes,5,opt,name=echo,proto3" json:"echo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *Response) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Response) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "skillreview.Request")
	proto.RegisterType((*Response)(nil), "skillreview.Response")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0xad, 0xd6, 0x4e, 0x41, 0x24, 0x28, 0x04, 0xf1, 0x20, 0x3d, 0x79, 0xea, 0x41,
	0x0f, 0x9e, 0xfc, 0x07, 0x0a, 0x12, 0x7f, 0x41, 0x5a, 0x86, 0xdd, 0xb0, 0x4d, 0xd2, 0xcd, 0x64,
	0xbb, 0xf7, 0xfd, 0xe5, 0x4b, 0xd2, 0x2c, 0xdb, 0xdd, 0xdb, 0x9b, 0x07, 0x6f, 0xe6, 0x7d, 0x03,
	0xd0, 0x49, 0xc2, 0x76, 0x74, 0xd6, 0x5b, 0x56, 0xd3, 0x46, 0x0d, 0x83, 0xc3, 0x49, 0xe1, 0xbe,
	0xf9, 0x82, 0x52, 0xe0, 0x76, 0x87, 0xe4, 0x19, 0x83, 0xc2, 0x48, 0x8d, 0x3c, 0x7b, 0xcb, 0xde,
	0x2b, 0x11, 0x35, 0xe3, 0x50, 0x6a, 0x24, 0x92, 0x2b, 0xe4, 0x37, 0xd1, 0x3e, 0x8d, 0xcd, 0x21,
	0x83, 0x7b, 0x81, 0x34, 0x5a, 0x43, 0xc8, 0x1e, 0x21, 0x47, 0x33, 0xa5, 0x64, 0x90, 0xec, 0x15,
	0x2a, 0xaf, 0x34, 0x92, 0x97, 0x7a, 0x4c, 0xd1, 0xb3, 0x11, 0xd6, 0x4e, 0xe8, 0x48, 0x59, 0xc3,
	0xf3, 0x79, 0x6d, 0x1a, 0x97, 0x07, 0x8b, 0x8b, 0x83, 0xa1, 0x1e, 0xf6, 0x6b, 0xcb, 0x6f, 0xe7,
	0x7a, 0x41, 0x7f, 0xfc, 0x40, 0xfd, 0x1f, 0x60, 0x44, 0x84, 0x61, 0xdf, 0xf0, 0xf0, 0xe7, 0x6c,
	0x8f, 0x44, 0xbf, 0x29, 0xf4, 0xd4, 0x2e, 0x60, 0xdb, 0x44, 0xfa, 0xf2, 0x7c, 0xe5, 0xce, 0x14,
	0xdd, 0x5d, 0xfc, 0xcf, 0xe7, 0x31, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x19, 0xe6, 0xeb, 0x2d, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SkillReviewClient is the client API for SkillReview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SkillReviewClient interface {
	ProcessMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type skillReviewClient struct {
	cc *grpc.ClientConn
}

func NewSkillReviewClient(cc *grpc.ClientConn) SkillReviewClient {
	return &skillReviewClient{cc}
}

func (c *skillReviewClient) ProcessMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/skillreview.SkillReview/ProcessMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillReviewServer is the server API for SkillReview service.
type SkillReviewServer interface {
	ProcessMessage(context.Context, *Request) (*Response, error)
}

// UnimplementedSkillReviewServer can be embedded to have forward compatible implementations.
type UnimplementedSkillReviewServer struct {
}

func (*UnimplementedSkillReviewServer) ProcessMessage(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMessage not implemented")
}

func RegisterSkillReviewServer(s *grpc.Server, srv SkillReviewServer) {
	s.RegisterService(&_SkillReview_serviceDesc, srv)
}

func _SkillReview_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillReviewServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillreview.SkillReview/ProcessMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillReviewServer).ProcessMessage(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SkillReview_serviceDesc = grpc.ServiceDesc{
	ServiceName: "skillreview.SkillReview",
	HandlerType: (*SkillReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _SkillReview_ProcessMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base.proto",
}
